import mongoose from 'mongoose';

const GroupSchema = new mongoose.Schema({
  // groupid will be generated by mongoDB
  name: {
    type: String,
    trim: true,
    unique: 'Group already exists',
    required: 'Group Name is required',
  },
  updated: Date,
  created: {
    type: Date,
    default: Date.now,
  },
  about: String,
  user_ids: [String]
});

export default mongoose.model('Group', GroupSchema);
